# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 490d8f709f78137faa14ec07200afc616f5eb29c5affd6e06f03b35281893f284797769f40bc163a91ba92bd2eafa2471f78d5bb916b72dd1c9f49641103c32b

test:
  secret_key_base: db0b6840f7646997e337f488bab1865f0681674b79969a33fdf85763e9a903a03ec5a7f3aac7307e948704dbe2a2ebe3b51248986ab72c0adb03ecac6466e535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
